# Generated by Django 3.2.17 on 2023-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mock_question',
            name='opt_1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mock_question',
            name='opt_2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mock_question',
            name='opt_4',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mock_question',
            name='right_opt',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_submitted',
            name='Submitted_Answer',
            field=models.TextField(max_length=100),
        ),
    ]
