# Generated by Django 3.2.17 on 2023-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230212_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mock_question',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='mock_question',
            name='time_limit',
        ),
        migrations.AlterField(
            model_name='mock_question',
            name='opt_3',
            field=models.TextField(max_length=100),
        ),
    ]
