# Generated by Django 3.2.17 on 2023-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230212_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mock_question',
            name='opt_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mock_question',
            name='opt_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mock_question',
            name='opt_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mock_question',
            name='opt_4',
            field=models.CharField(max_length=100),
        ),
    ]
