# Generated by Django 3.2.17 on 2023-02-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230212_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mock_question',
            name='right_opt',
            field=models.CharField(max_length=100),
        ),
    ]
