# Generated by Django 3.2.17 on 2023-02-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mock_question_right_opt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_submitted',
            name='Submitted_Answer',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
    ]
