# Generated by Django 3.2.17 on 2023-04-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_user_submitted_submitted_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_submitted',
            name='Submitted_Answer',
            field=models.TextField(blank=True, default='null', max_length=100),
        ),
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.TextField(blank=True, default='null', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'leaderboard',
            },
        ),
    ]
