# Generated by Django 3.2.17 on 2023-04-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230418_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.TextField(blank=True, default='null', max_length=100),
        ),
    ]
