# Generated by Django 3.2.17 on 2023-04-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_leaderboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='percent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
